### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by designmatty** [azavea/summer-of-maps-website#29]
The site is ready to be deployed to production.
Should be deployed to `https://www.summerofmaps.com/`

**Comment by danford1** [comment]
@designmatty would it be possible to take screen shots of the current SoM site for posterity?
Also, I'm actively working on @eneedham 's proposed edits to copy. I'll be pushing a branch today.

**Comment by danford1** [comment]
All copy edits merged in #30. @designmatty I took care of the screenshots and saved them to the fileshare.
Fileshare location:
`/projects/Azavea_SummerOfMaps/documents/design/website_redesign/2018/screenshots`
