### ISSUE TITLE
Verify email configuration of Screendoor

### ISSUE THREAD

**Issue by hectcastro** [azavea/summer-of-maps-website#53]
Ensure that any configuration required by us is setup properly. If email issues are occurring because email are coming from our domain, it may be related to DKIM.

**Comment by tnation14** [comment]
@hectcastro could you clarify the problem that led to the creation of this issue? It's not clear what we'd need to test in order to verify the configuration, and I don't see any mention of Screendoor in this repo.

**Comment by eneedham** [comment]
It's possible that we will move away from Screendoor and transition entirely to Google Hire. I will check in with Karissa.

**Comment by kjjustice** [comment]
We have moved from Screendoor to Google Hire for all student candidate applications (so should have no issue there), however, organizations still submit their project applications through Screendoor.  I believe Robert is the Screendoor account owner.

**Comment by tnation14** [comment]
I reached out to Robert to see if I could get access to the Screendoor admin account. Marking this as blocked until he replies.

**Comment by tnation14** [comment]
I asked Robert for access to the Screendoor account; marking this as blocked until we get a login.

**Comment by tnation14** [comment]
I reached out to Robert to see if I could get access to the Screendoor admin account. Marking this as blocked until we have a login.

**Comment by rbreslow** [comment]
I spoke with Robert last Thursday and he made me an Admin on Screendoor. @kjjustice and @eneedham, Robert said you were also Admins.

I reached out to our account manager, Josh Goldstein (jgoldstein@thecitybase.com).

**Comment by rbreslow** [comment]
I followed up with Josh. He hasn't responded since I sent the first email 11 days ago. I also forwarded the email to support@dobt.co.

**Comment by rbreslow** [comment]
Josh responded and is looking into things.

**Comment by rbreslow** [comment]
P.S. Just FYI emails come from noreply@dobt.co but will mention your
organization name. We're making a few improvements to Sendgrid (our
emailing tool) which might have caused this bug. I'll let you know when
it's resolved. Sorry again for the inconvenience.
