### ISSUE TITLE
Advance SoM website stage

### ISSUE THREAD

**Issue by rossbernet** [azavea/summer-of-maps-website#83]
Hey @designmatty 

SoM is DONE for summer 2020! We made it.

We need to advance the website to the next phase.

@dmcglone and I need to add the project descriptions for the fellows. We are waiting on one description, but what is the best format to provide that?

Should Daniel and I fill in this template for each one:
https://github.com/azavea/summer-of-maps-website/tree/master/_projects
?

**Comment by designmatty** [comment]
I'd say put things up in a google doc but organize it according to the template. 

Checkout [a previous project description](https://raw.githubusercontent.com/azavea/summer-of-maps-website/master/_projects/2019/2019-congreso-de-latinos-unidos.md) to see what it looks like filled out.

You'll notice there is a section for images (don't worry about featured image, I'll be making those), I'll need to know where the project images live on the fileshare so I can get them sized down and setup in the repo.
